name: Send dispatch to repositories oc.cupsd.18.04 and oc.user

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch repository oc.cupsd.18.04
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.cupsd.18.04
          event-type: dispatch-from-cups

      - name: Dispatch repository oc.user
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.user
          event-type: dispatch-from-cups
